config/routes.rb
BucketList::Application.routes.draw do
  resources :steps

  resources :lists do
    resources :steps do
      member do
        post :complete
      end
    end
  end

  root :to => 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :name, :reason, :date

  has_many :steps
end

app/models/step.rb
class Step < ActiveRecord::Base
  attr_accessible :complete, :description, :list_id

  belongs_to :list
  scope :complete, where(:complete => true)
  scope :incomplete, where(:complete => false)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	def index
		@lists = List.all
	end

	def new
		@list = List.new
	end

	def create
		@list = List.new(params[:list])
		if @list.save
			redirect_to lists_url
		else
			render action: "new"
		end
	end
	def edit
		@list = List.find(params[:id])
	end

	def update
		@list = List.find(params[:id])

		if @list.update_attributes(params[:list])
			redirect_to lists_path
		else
			render action: "edit"
		end
	end

	def show
		@list = List.find(params[:id])
	end

	def destroy
		@list = List.find(params[:id])
		@list.destroy
		redirect_to lists_url
	end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
	def create
		@list = List.find(params[:list_id])
		@step = @list.steps.new(params[:step])
		if @step.save
			redirect_to list_url(@list)
		else
			redirect_to list_url(@list)
		end
	end
	def complete
		@list = List.find(params[:list_id])
		@step = Step.find(params[:id])
		@step.complete = true
		@step.save
		redirect_to list_url(@list)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BucketList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/lists/edit.html.erb
<h2>Edit <%= @list.name %></h2>

<%= form_for @list do |form| %>
	<div>
		<%= form.label :name %><br />
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :reason %><br />
		<%= form.text_field :reason %>
	</div>

	<p><%= form.submit %></p>
	<% end %>

app/views/lists/index.html.erb
<div class="hero-unit">
  <h1>Good Luck With That</h1>
  <p class="descrip">A place to track all the things you'll never get around to doing.</p>
  <p class="button"><%= link_to "Get Started", new_list_url, :class => "brn btn-primary btn-large" %></p>
</div>
 
<table class="table table-striped">
  <thead>
    <th>Name</th>
    <th>Reason</th>
    <th>Date</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td class="title"><%= link_to list.name, list_path(list) %></td>
        <td><%= list.reason %></td>
        <td><%= list.date %></td>
        <td><%= link_to "Edit", edit_list_path(list) %> | <%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lists/new.html.erb
<h2>Create New Bucket List</h2>
<%= form_for @list do |form| %>
	<div>
		<%= form.label :name %><br />
		<%= form.text_field :name %>
	</div>

	<div>
		<%= form.label :reason %><br />
		<%= form.text_field :reason %>
	</div>

	<div>
		<%= form.label :date %><br />
		<%= form.text_field :date %>
	</div>

	<p><%= form.submit %></p>
	<% end %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<p><%= @list.reason %></p>
 
<h3>Steps I Need to Take</h3>
<ul>
  <% @list.steps.incomplete.each do |single_step| %>
    <li>
      <%= single_step.description %> | <%= single_step.complete %>
      <%= button_to "Complete", complete_list_step_path(@list.id, single_step.id) %>
    </li>
  <% end %>
</ul>
 
<h3>Steps I Completed!</h3>
<ul>
  <% @list.steps.complete.each do |single_step| %>
    <li><%= single_step.description %></li>
  <% end %>
</ul>
 
<h2>Add Step</h2>
<p>Baby steps will help you achieve your goal</p>
 
<%= form_for [@list, @list.steps.new]  do |form| %>
  <%= form.text_field :description %>
  <%= form.submit %>
<% end %>